# 🔎 kubernetes ebs driver install 
#  GitHub --> Example/kubernetes --> static-provisioning --> manifest --> pv.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebs-static
spec:
  accessModes:
  - ReadWriteOnce # 🔎 kubernetes volume --> check here, Persistant Volume in static  
  capacity:
    storage: 20Gi # <-- we created 20GB in AWS Console, thats why we giving 20 here.
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle:                   # < -- AWS Console lo create ina 20GB di Volume ID ekkada mention cheyali. 

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-static  # <-- changing to static
spec:
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
  volumeName: ebs-static  # I am claming from ebs-static, thats why we kept. 
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

--- 

apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  nodeSelector:
    topology.kubernetes.io/zone: us-east-1c  # <-- change = to : symbol. 
  containers:
  - name: nginx
    image: nginx
    volumeMounts:   # docker run -v host-path:container-path
    - name: persistent-storage
      mountPath: /usr/share/nginx/html  # <-- endulo store chey ani chepputunnam.
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: ebs-static  # < -- manam clear gha chepputunnam, ebs-static lo store chey ani (PVC) lo. Eee PVC velli PV lo store avutmdhi. it means EBS only. 

# Kubernetes ki yemi chepputunam, Nvu ee Pod ni create chetappudu ee labels ni, line no 40 ane label ni consider cheysi, andulopala preference vachhesi andhulopla ee pod ni create cheyamani. US-EAST-1C lo yevi ite nodes unnayyo, aa Nodes lopala ee Pod ni create cheyamani chepputunam. 