apiVersion: v1
kind: Pod # A pod has 1 or multiple container 
metadata:
  name: multi-container
  labels: # mandotory kadu but chala important evvatam.
    project: roboshop
    Purpose: multi-container-demo
spec:
  containers:
  - name: nginx
    image: nginx
  - name: almalinux
    image: almalinux:9 
    command: [ "sleep", "1000" ]

# nginx image anukondi, adhi yenti nginx -d deamon off anedhi continues running lo untundhi, like infinate times.
# 