# 🔍 kubernetes secretref from pod

apiVersion: v1
kind: Pod
metadata:
  name: env-secret
spec:
  containers:
    - name: nginx
      image: nginx
      envFrom:
        - secretRef:  # <---
            name: pod-screte  # <--- 

# edi decode ipoyee autoimatic gha akkadiki add ipotumdhii.. 