# 🔍 kubernetes service
apiVersion: v1
kind: Service # yee rakamina resource vadutunnav, aa resources type
metadata:
  name: nginx-loadbalancer # aa Resources type ki oka peru 
  labels:
    purpose: service-loadbalancer-demo
spec:
  type: LoadBalancer # <--- capital letters L,B 
  selector:
    purpose: service-loadbalancer-demo
    project: roboshop
    environment: dev
  ports:
    - protocol: TCP
      port: 80 # service port
      targetPort: 80 # container port 


---
apiVersion: v1
kind: Pod # resource type
metadata:
  name: nginx-loadbalancer # aa Resources type ki oka peru 
  labels: 
    purpose: service-loadbalancer-demo
    project: roboshop
    environment: dev
spec:
  containers:
  - name: nginx
    image: nginx
