apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: liveness-http
spec:
  containers:
  - name: liveness
    image: nginx
    livenessProbe:
      tcpSocket:
        port: 80 # --> means port number 80 is open indha.. leda ani. 
      initialDelaySeconds: 30
      periodSeconds: 10
    readinessProbe:
      httpGet:
        path: /
        port: 80  # --> miku response vastumdha leda port number 80 pina.. 
      initialDelaySeconds: 40
      periodSeconds: 3  # Every 3 sec ki kubernetes check chesukuntumdhi. Yemi ani, Response vastumdha (OR) Rada ani, Response rakapote Restart chestumdhi anamaat. That is called Self-Healing. 